//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sem3.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string FeedbackText { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual User User { get; set; }
    }
}
