//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sem3.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineRechargeDBEntities : DbContext
    {
        public OnlineRechargeDBEntities()
            : base("name=OnlineRechargeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<ContactPoint> ContactPoints { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PostpaidBill> PostpaidBills { get; set; }
        public virtual DbSet<RechargePlan> RechargePlans { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<SiteContent> SiteContents { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionScript> TransactionScripts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserService> UserServices { get; set; }
        public virtual DbSet<UserServiceSetting> UserServiceSettings { get; set; }
    }
}
