//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sem3.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargePlan
    {
        public int PlanID { get; set; }
        public string PlanType { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> TalkTimeMinutes { get; set; }
        public Nullable<int> DataMB { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Operator { get; set; }
        public string PlanName { get; set; }
    }
}
